### ISSUE TITLE
你好 Mod + `123qweas tag 跳转 这个不能用呀 

### ISSUE THREAD

**Issue by evan886** [alswl/awesome#2]
Mod + `123qweas tag 跳转 这个不能用呀  还要配置哪里么

**Comment by alswl** [comment]
新版的 awesome 3.5 修改了不少 API，并且向后不兼容。

我开了一个分支 `fix/awesome-3.5` 正在修正，但是因为平时工作用 Mac，只有回家才有 Linux，所以进展缓慢。

**Comment by evan886** [comment]
哦哦  厉害了我的哥，THX

**Comment by alswl** [comment]
@evan886 这个版本算是 beta，因为我自己不在使用 😂 ，所以出现问题后响应速度会比较慢。

所以你最好自己看懂代码，可以自行修改修改。

**Comment by alswl** [comment]
@evan886 我看了一眼代码，master 代码是最新的，`fix/awesome-3.5` 反而是五个月前做的尝试性修改，然后一堆问题，我就重新同步了官方的默认配置，在 master 里面做调整（三个月前）。

所以 master 代码应该可用，你遇到什么问题？把错误截图抛出来看看。

**Comment by alswl** [comment]
@evan886 最新 master 已经支持了 awesome 4.2。
